# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strawberry < Formula
  desc "An awesome static site generator based on Hugo."
  homepage ""
  version "0.25.0"

  depends_on "go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/strawberry-tools/strawberry/releases/download/v0.25.0/strawberry-v0.25.0-macos-amd64.tar.gz"
    sha256 "d0ef19a321220075021dd31550844843e8e474c972fa5a858b960aa8daa1086b"

    def install
      bin.install "strawberry"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/strawberry-tools/strawberry/releases/download/v0.25.0/strawberry-v0.25.0-macos-arm64.tar.gz"
    sha256 "bb232d364985fa5c18258419190e9292b6bbc30a3d10cce6a18e8edad924da64"

    def install
      bin.install "strawberry"
    end
  end

  test do
    site = testpath/"hops-yeast-malt-water"
    system "#{bin}/strawberry", "new", "site", site
    assert_predicate testpath/"#{site}/config.toml", :exist?
  end
end
