# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strawberry < Formula
  desc "An awesome static site generator based on Hugo."
  homepage "https://www.StrawberrySSG.com"
  version "0.16.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/strawberryssg/strawberry-v0/releases/download/v0.16.0/strawberry-v0.16.0-macos-amd64.tar.gz"
    sha256 "58284d35e96d3a26044c3401cbc578893cf58940944c4ceae99bcbd4f68aa8a3"
  end

  depends_on "go"

  def install
    bin.install "strawberry"
  end

  test do
    site = testpath/"hops-yeast-malt-water"
    system "#{bin}/strawberry", "new", "site", site
    assert_predicate testpath/"#{site}/config.toml", :exist?
  end
end
