# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strawberry < Formula
  desc "An awesome static site generator based on Hugo."
  homepage ""
  version "0.24.1"

  depends_on "go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/strawberry-tools/strawberry/releases/download/v0.24.1/strawberry-v0.24.1-macos-amd64.tar.gz"
    sha256 "cdf7c6d9e7e122c5e3509bda2a321c6dfc4057e34093e75183ee6148d2f8bfab"

    def install
      bin.install "strawberry"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/strawberry-tools/strawberry/releases/download/v0.24.1/strawberry-v0.24.1-macos-arm64.tar.gz"
    sha256 "6983dee75f2c14eaf820e446d23432fe95c77f7ac5ec9dd80cc4f0d2be69e0ca"

    def install
      bin.install "strawberry"
    end
  end

  test do
    site = testpath/"hops-yeast-malt-water"
    system "#{bin}/strawberry", "new", "site", site
    assert_predicate testpath/"#{site}/config.toml", :exist?
  end
end
