# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valerie < Formula
  desc "An HTML schema validator."
  homepage "https://github.com/strawberry-tools/valerie"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/strawberry-tools/valerie/releases/download/v0.4.0/valerie-v0.4.0-macos-amd64.tar.gz"
      sha256 "df23d823fb3cd00d464eac0d3a241c466c188b309965cf42cd766b7f123f5a4e"

      def install
        bin.install "valerie"
        bash_completion.install "completions/arc.bash" => "valerie"
        fish_completion.install "completions/arc.fish"
        zsh_completion.install "completions/arc.zsh" => "_valerie"
      end
    end
    on_arm do
      url "https://github.com/strawberry-tools/valerie/releases/download/v0.4.0/valerie-v0.4.0-macos-arm64.tar.gz"
      sha256 "a89f01b79a6a6788b614b7bc895aec3773398b1022174d96623d511ce15b50fa"

      def install
        bin.install "valerie"
        bash_completion.install "completions/arc.bash" => "valerie"
        fish_completion.install "completions/arc.fish"
        zsh_completion.install "completions/arc.zsh" => "_valerie"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/strawberry-tools/valerie/releases/download/v0.4.0/valerie-v0.4.0-linux-amd64.tar.gz"
        sha256 "698142570516ef894792bd5cca994fe0be81517041cacec084986f73ab8520f0"

        def install
          bin.install "valerie"
          bash_completion.install "completions/arc.bash" => "valerie"
          fish_completion.install "completions/arc.fish"
          zsh_completion.install "completions/arc.zsh" => "_valerie"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/strawberry-tools/valerie/releases/download/v0.4.0/valerie-v0.4.0-linux-arm64.tar.gz"
        sha256 "1c15b84df251093efa65b279ade4c6212c6c8910f44ecea5df6fd00d5acbcb0c"

        def install
          bin.install "valerie"
          bash_completion.install "completions/arc.bash" => "valerie"
          fish_completion.install "completions/arc.fish"
          zsh_completion.install "completions/arc.zsh" => "_valerie"
        end
      end
    end
  end

  test do
    system "#{bin}/valerie", "help"
  end
end
